# **스테이지 1. 데이터 불러오기**

## **Step 1. 데이터 불러오기**

데이터분석을 하기에 앞서, 데이터분석을 진행할 공간이 필요할 거에요!<br>
저희는 **Google Colab**에서 작업하도록 하겠습니다~<br>

🙋 `Google Colab`이란?

구글 코랩은 주피터 노트북을 기반으로 분석할 수 있는 작업 공간을 제공합니다!<br>
클라우드 컴퓨팅을 기반으로 무료 작업 공간과, 고성능의 GPU를 지원하기 때문에<br>
데이터 입문자부터 수많은 데이터 과학자들이 사용하는 플랫폼이랍니다.<br>

구글 코랩이 아니더라도 개인 컴퓨터에서 분석을 진행할 수도 있어요!<br>
Python의 **Anaconda** 패키지를 활용하면 쉽게 분석 환경을 구축할 수 있습니다.

먼저 구글 드라이브에 연결하도록 하겠습니다.<br>
구글 코랩을 사용하지 않는 분들은 넘어가시면 됩니다~

In [1]:
# drive에 연결합니다.
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# 현재 데이터가 있는 공간으로 작업 경로를 변경해줍니다.
%cd "/content/drive/MyDrive/ML_Data/Dacon/데이크루6기/신용카드/open"

Mounted at /content/drive
/content/drive/MyDrive/ML_Data/Dacon/데이크루6기/신용카드/open

이제 데이터를 준비해주겠습니다!<br>
먼저 판다스(pandas) 라이브러리(library)를 통해 **CSV 파일의 데이터**를 불러오도록 하겠습니다!

🙋 `pandas` 라이브러리가 무엇인가요?<br>
판다스 라이브러리는 데이터 분석을 위한 라이브러리로, Python 프로그래밍 언어를 위한 라이브러리입니다!<br>
빠르고 범용성이 좋기 때문에 데이터 분석에 필수적인 라이브러리라고 할 수 있죠!<br>
판다스 라이브러리는 이번에 저희가 다루게 될 데이터처럼 **행(row)**과 **열(column)**로<br> 이루어진 2차원 데이터를 다루는데 유용한 패키지입니다.

🙋 그렇다면 `CSV` 파일은 무엇인가요?<br>
CSV 파일은 **Comma-Separated Values**의 약자로, 몇 가지 필드를 **쉼표(,)**로 구분한 텍스트 파일을 말합니다.<br>
데이터 분석 프로젝트의 일반적인 데이터 형식으로, CSV 파일은 매우 빈번하게 사용된답니다!

이번 프로젝트에서 다룰 데이터들은 다음과 같습니다!<br>
세 개의 데이터 파일의 형식은 모두 CSV 파일입니다~<br>
* 🚀 `train.csv`: 데이터 분석 모델을 학습(train)시키기 위한 데이터 파일입니다!
* 📝 `test.csv`: 학습된 모델을 바탕으로 결과를 예측하기 위한 데이터 파일입니다!
* 🚩 `sample_submission.csv`: `test.csv`을 통해 예측된 결과를 제출하기 위한 파일입니다!

우선 `pandas` 라이브러리를 별칭으로 간단하게 `pd`라는 이름으로 불러오도록 하겠습니다!<br>
다음으로 🚩 `sample_submission.csv` 파일을 불러오도록 하겠습니다!<br>

`read_csv()` 함수는 CSV 파일을 읽어서 데이터프레임(DataFrame) 형식으로 반환합니다.<br>
데이터프레임은 **행(row)**과 **열(column)**로 이루어진 테이블 형태의 데이터입니다.<br>
`read_csv()` 함수는 다양한 매개변수를 받아 데이터를 읽을 수 있는데,<br>
코드에서는 파일 경로(`'sample_submission.csv'`)를 문자열로 전달하였습니다.<br>

In [2]:
# pandas 패키지를 pd라는 별칭으로 불러옵니다.
import pandas as pd

# sample_submission.csv 파일을 submission이라는 변수에 할당합니다.
submission = pd.read_csv('sample_submission.csv')

🔍️ **Inst.**<br>
이번에는 직접 문제를 풀어보도록 하겠습니다!<br>
✔️ `pandas` 라이브러리를 `pd`라는 별칭으로 불러와보세요!<br>
✔️ `train.csv`, `test.csv` 파일을 각각 train, test 변수에 저장해보세요!

In [3]:
# pandas 패키지를 pd 라는 별칭으로 import 해봅시다!


# pandas 내에 있는 read_csv 함수를 사용해 train.csv, test.csv 파일을 각각 train, test라는 이름으로 불러와봅시다!

💡 **Hint.**<br>
**pandas** 라이브러리를 로드하고 `pd.read_csv()`를 사용해볼까요?

✅ **Solution.**<br>
정답은 아래와 같습니다!

In [4]:
# pandas 패키지를 pd 라는 별칭으로 import 해봅시다!
import pandas as pd

# pandas 내에 있는 read_csv 함수를 사용해 train.csv, test.csv 파일을 각각 train, test라는 이름으로 불러와봅시다!
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

## **Step 2. 간단하게 데이터 살펴보기**

### **1. head() / tail()**

여기까지 잘 따라오셨나요?<br>
좋습니다! 🔥🔥<br>
다음으로는 불러온 train 데이터를 살펴보도록 하겠습니다!

데이터프레임에는 `head()`와 `tail()` 메서드가 존재합니다!<br>
`head()` 메서드는 데이터프레임(DataFrame)의 첫 번째부터 지정된 개수의 행(row)을 반환하는 메서드입니다.<br>
반면, `tail()` 메서드는 데이터프레임(DataFrame)의 마지막부터 지정된 개수의 행(row)을 반환하는 메서드입니다.<br>
`head()`와 `tail()` 메서드는 일부 행을 확인하고 데이터의 구조와 내용을 파악하는 데 사용되는데,<br>
특히 큰 데이터프레임이나 데이터셋에서 데이터의 형태를 파악하고자 할 때 주로 사용합니다.

In [5]:
submission.head()

   index  0  1  2
0  26457  0  0  0
1  26458  0  0  0
2  26459  0  0  0
3  26460  0  0  0
4  26461  0  0  0

**결과 해석**<br>
제출할 submission 데이터는 `index`와 `credit`의 결과를 나타내는 `0`, `1`, `2` 칼럼(column)으로 이루어져 있습니다.<br>
그러나 모든 `0`, `1`, `2` 데이터가 0으로 이루어져 있기 때문에,<br>
이번 프로젝트에서는 각 `index`에 따른 고객의 신용도를 예측하는 문제임을 알 수 있습니다.<br>
따라서, `test`고객 데이터의 신용도 예측 결과에 대한 확률로 `index`의 값을 모두 채우면 됩니다.

이를 위해 모델링을 통해 각 `index`에 따른 고객의 신용도를 예측하고,
이를 `0`, `1`, `2` 칼럼에 대입하여 최종적인 `submission` 데이터를 생성합니다.

[sample_submission.csv]

* index: 고객 번호
* 0, 1, 2: 신용도 컬럼

🔍️ **Inst.**<br>
이번에는 직접 데이터를 확인해보도록 하겠습니다!<br>
✔️ train 데이터의 하위 행 5개를 확인해보세요!<br>

In [6]:
# train 데이터의 하위 행 5개를 확인합니다.

💡 **Hint.**<br>
train 데이터의 `tail()` 메서드를 사용해볼까요?

✅ **Solution.**<br>
정답은 아래와 같습니다!

In [7]:
# train 데이터의 하위 행 5개를 확인합니다.
train.tail()

,index,gender,car,reality,child_num,income_total,income_type,edu_type,family_type,house_type,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,work_phone,phone,email,occyp_type,family_size,begin_month,credit
26452,26452,F,N,N,2,225000.0,State servant,Secondary / secondary special,Married,House / apartment,-12079,-1984,1,0,0,0,Core staff,4.0,-2.0,1.0
26453,26453,F,N,Y,1,180000.0,Working,Higher education,Separated,House / apartment,-15291,-2475,1,0,0,0,NaN,2.0,-47.0,2.0
26454,26454,F,Y,N,0,292500.0,Working,Secondary / secondary special,Civil marriage,With parents,-10082,-2015,1,0,0,0,Core staff,2.0,-25.0,2.0
26455,26455,M,N,Y,0,171000.0,Working,Incomplete higher,Single / not married,House / apartment,-10145,-107,1,0,0,0,Laborers,1.0,-59.0,2.0
26456,26456,F,N,N,0,81000.0,Working,Secondary / secondary special,Civil marriage,House / apartment,-19569,-1013,1,0,0,0,Security staff,2.0,-9.0,2.0

### **2. columns**

데이터프레임 객체는 `columns` 속성(attribute)를 가지고 있습니다!<br>
데이터프레임의 `columns` 속성은 열 이름들을 반환하여 변수명을 확인할 수 있습니다.
`columns` 속성을 사용함으로써 열 이름을 변경하거나, 열의 순서를 변경하는 작업을 수행할 수 있습니다.

🔍️ **Inst.**<br>
직접 문제를 풀어보도록 하죠!<br>
✔️ train 데이터프레임의 컬럼들을 확인해보세요!<br>

In [8]:
# train 데이터의 컬럼들을 확인합니다.

💡 **Hint.**<br>
train 데이터의 `columns` 속성(attribute)를 사용해볼까요?

✅ **Solution.**<br>
정답 공개합니다!

In [9]:
# train 데이터의 컬럼들을 확인합니다.
train.columns

Index(['index', 'gender', 'car', 'reality', 'child_num', 'income_total',
       'income_type', 'edu_type', 'family_type', 'house_type', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_MOBIL', 'work_phone', 'phone', 'email',
       'occyp_type', 'family_size', 'begin_month', 'credit'],
      dtype='object')

### train 데이터의 컬럼은 다음과 같습니다.
* index
* gender: 성별
* car: 차량 소유 여부
* reality: 부동산 소유 여부
* child_num: 자녀 수
* income_total: 연간 소득
* income_type: 소득 분류
							['Commercial associate', 'Working', 'State servant', 'Pensioner', 'Student']

* edu_type: 교육 수준
							['Higher education' ,'Secondary / secondary special', 'Incomplete higher', 'Lower secondary', 'Academic degree']

* family_type: 결혼 여부
							['Married', 'Civil marriage', 'Separated', 'Single / not married', 'Widow']

* house_type: 생활 방식
							['Municipal apartment', 'House / apartment', 'With parents',

							 'Co-op apartment', 'Rented apartment', 'Office apartment']

* DAYS_BIRTH: 출생일
							데이터 수집 당시 (0)부터 역으로 셈, 즉, -1은 데이터 수집일 하루 전에 태어났음을 의미

* DAYS_EMPLOYED: 업무 시작일
							데이터 수집 당시 (0)부터 역으로 셈, 즉, -1은 데이터 수집일 하루 전부터 일을 시작함을 의미

							양수 값은 고용되지 않은 상태를 의미함

* FLAG_MOBIL: 핸드폰 소유 여부
* work_phone: 업무용 전화 소유 여부
* phone: 전화 소유 여부
* email: 이메일 소유 여부
* occyp_type: 직업 유형
* family_size: 가족 규모
* begin_month: 신용카드 발급 월
							데이터 수집 당시 (0)부터 역으로 셈, 즉, -1은 데이터 수집일 한 달 전에 신용카드를 발급함을 의미

* credit: 사용자의 신용카드 대금 연체를 기준으로 한 신용도
							=> 낮을 수록 높은 신용의 신용카드 사용자를 의미함

### **3. shape**

여기까지 잘 따라오셨나요?	😁 다음으로 알아볼 것은 `shape` 속성입니다!<br>

데이터프레임의 `shape` 속성은 데이터프레임의 크기를 반환하는 속성입니다!<br>
우리는 `shape` 속성을 통해 데이터프레임의 행과 열을 확인해볼 수 있습니다.

🔍️ **Inst.**<br>
문제를 풀어보겠습니다!<br>
✔️ train 데이터프레임의 행과 열의 개수를 확인해보세요!<br>

In [10]:
# train 데이터의 행과 열의 개수를 확인합니다.

💡 **Hint.**<br>
train 데이터의 `shape` 속성(attribute)를 사용해볼까요?

✅ **Solution.**<br>
정답 공개합니다!

In [11]:
# train 데이터의 행과 열의 개수를 확인합니다.
train.shape

(26457, 20)

와우! 정말 잘 따라오셨어요~ <font color=blue>**크레딧가디언즈**</font>와 함께하는 데이터 분석 첫 번째 스테이지가 끝났습니다! 🎉<br>
다음 스테이지는 **'데이터 확인하기'** 스테이지가 준비되어 있답니다!<br>
다음 스테이지도 기대해주세요! 😊